export const UPDATE_PUZZLE_IMAGE_STATE = Symbol('UPDATE_PUZZLE_IMAGE_STATE')

export const UPDATE_IMAGE_GRID_STATE = Symbol('UPDATE_IMAGE_GRID_STATE')

export const UPDATE_FOR_SHARE_STATE = Symbol('UPDATE_FOR_SHARE_STATE')

export const UPDATE_FOR_PUZZLE_STATE = Symbol('UPDATE_FOR_PUZZLE_STATE')

export const SET_LANGUAGE_TO_ZH = Symbol('SET_LANGUAGE_TO_ZH')
export const SET_LANGUAGE_TO_EN = Symbol('SET_LANGUAGE_TO_EN')
export const SWITCH_LANGUAGE = Symbol('SWITCH_LANGUAGE')