export const UPDATE_PUZZLE_IMAGE_STATE = Symbol('UPDATE_PUZZLE_IMAGE_STATE')

export const UPDATE_IMAGE_GRID_STATE = Symbol('UPDATE_IMAGE_GRID_STATE')

export const UPDATE_FOR_SHARE_STATE = Symbol('UPDATE_FOR_SHARE_STATE')